---
name: checkstyle (NPM)
# yamllint disable-line rule:truthy
on: [push, pull_request]
jobs:
  checkstyle-npm:
    runs-on: ubuntu-latest
    container:
      image: registry.opensuse.org/devel/openqa/qem-dashboard/containers/opensuse/qem-dashboard_devel:latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6
      with:
        fetch-depth: 0
    - name: Bootstrap container dependencies
      run: |
        if ! command -v git &>/dev/null || ! command -v make &>/dev/null || ! command -v npm &>/dev/null || ! command -v gitlint &>/dev/null; then
          echo "Installing missing system packages..."
          zypper in -y -C git-core make nodejs-default npm python313-gitlint
        fi
    - name: Fix git permissions
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
    - name: Install JS dependencies
      run: npm clean-install --ignore-scripts
    - name: Run checkstyle
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          make checkstyle-npm COMMIT_ARGS="--commits origin/${{ github.base_ref }}..HEAD --verbose"
        else
          BEFORE="${{ github.event.before }}"
          AFTER="${{ github.event.after }}"
          if [ "$BEFORE" == "0000000000000000000000000000000000000000" ] || ! git cat-file -e "$BEFORE" >/dev/null 2>&1; then
            make checkstyle-npm COMMIT_ARGS="--verbose"
          else
            make checkstyle-npm COMMIT_ARGS="--commits $BEFORE..$AFTER --verbose"
          fi
        fi
