name: test
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  only-test:
    runs-on: ubuntu-latest
    container:
      image: registry.opensuse.org/devel/openqa/qem-dashboard/containers/opensuse/qem-dashboard_devel:latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6
      - name: Bootstrap container dependencies
        run: |
          if ! command -v git &>/dev/null || ! command -v make &>/dev/null || ! command -v npm &>/dev/null; then
            echo "Installing missing system packages..."
            zypper in -y -C git-core make gcc file-devel findutils perl-App-cpanminus nodejs-default npm
          fi
      - name: Fix git permissions
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Install JS dependencies
        run: make install-deps-js
      - name: Install Perl dependencies
        run: make install-deps-cpanm
      - name: Run all tests with coverage
        env:
          TEST_ONLINE: postgresql://postgres:postgres@postgres:5432/postgres
        run: make only-test-coverage
      - name: Check assets
        run: ls public/asset
      - name: Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cover -report Coveralls
